name: pv_forecast

channels:
  - conda-forge
  - defaults

dependencies:
 - jupyter=1.0.0
 - python=3.9.6
 - click=8.0.1
 - matplotlib=3.4.3
 - mlflow=1.2.0
 - numpy=1.21.2
 - ipympl=0.8.0
 - pandas=1.3.2
 - psycopg2=2.9.1
 - pytest=6.2.5
 - scikit-learn=0.24.2
 - tqdm=4.62.2
 - tensorflow=2.6.0
 - pytest=6.2.5
 - seaborn=0.11.2
 - flake8=3.9.2
 - pip=20.3.3
 - pip:
   - tensorflow-addons==0.14.0
